export enum NotificationType {
    PLACE = 'PLACE',
    PLACE_ACCEPTED = 'PLACE_ACCEPTED',
    PLACE_REJECTED = 'PLACE_REJECTED',

    PAYMENT = 'PAYMENT',
    PAYMENT_ACCEPTED = 'PAYMENT_ACCEPTED',
    PAYMENT_REJECTED = 'PAYMENT_REJECTED'
}
